    "Guardians of Sunshine"
    "Video Makers"
    "What Was Missing"
    "The Creeps"
    "Holly Jolly Secrets Part I"
    "Holly Jolly Secrets Part II"
    "Five Short Graybles" (grayble)
    "Hug Wolf"
    "BMO Noire"
    "Five More Short Graybles" (grayble)
    "Puhoy"
    "BMO Lost"
    "James Baxter the Horse"
    "Shh!"
    "Be More"
    "We Fixed a Truck"
    "Apple Wedding"
    "Ghost Fly"
    "Jake The Brick"
    "Chips and Ice Cream"
    "Graybles 1000+" (grayble)
    "All's Well That Rats Swell"
    "Football"
    "The More You Moe, The Moe You Know (Part I)"
    "The More You Moe, The Moe You Know (Part II)"
    "Angel Face"
    "Bad Jubies"
    "Horse and Ball"
    "The Invitation"
    "Whipple The Happy Dragon"
    "Imaginary Resources"
    "The Light Cloud"
    "Orb"
    "Skyhooks"
    "Ketchup"
    "Always BMO Closing"
    "Seventeen"
    "Come Along With Me"
    "BMO"
    "Business Time" (debut)
    "My Two Favorite People"
    "Evicted!"
    "What is Life?"
    "Donny"
    "Rainy Day Daydream"
    "Slow Love"
    "Power Animal"
    "Her Parents"
    "Conquest of Cuteness"
    "Too Young"
    "The Monster"
    "Fionna and Cake" (Fionna-world version, non-speaking cameo)
    "The New Frontier"
    "Dad's Dungeon"
    "Incendium"
    "Dream of Love"
    "Daddy's Little Monster"
    "In Your Footsteps"
    "Beyond this Earthly Realm"
    "Card Wars"
    "Gotcha!"
    "Burning Low"
    "King Worm" (dream cameo)
    "All the Little People" (Little Person)
    "Jake the Dad"
    "Davey"
    "Little Dude"
    "Bad Little Boy" (Fionna-world version, non-speaking)
    "A Glitch is a Glitch" (non-speaking cameo)
    "One Last Job"
    "Another Five More Short Graybles" (grayble)
    "Candy Streets"
    "Jake Suit"
    "Frost & Fire"
    "Too Old" (non-speaking cameo)
    "Earth & Water" (non-speaking cameo)
    "Time Sandwich" (cameo)
    "The Vault"
    "Love Games"
    "Box Prince"
    "Play Date"
    "The Pit
    "The Tower"
    "Sad Face"
    "Furniture & Meat"
    "Thanks for the Crabapples, Giuseppe"
    "Joshua and Margaret Investigations"
    "Everything's Jake"
    "The Visitor"
    "The Mountain"
    "Dark Purple"
    "Jermaine"
    "Hoots"
    "The Comet" (comet projection)
    "President Porpoise is Missing!"
    "Blank Eyed Girl"
    "Crossover"
    "The Hall of Egress"
    "Flute Spell"
    "Don't Look"
    "Beyond the Grotto" (Bee-Mo)
    "I Am a Sword"
    "The Music Hole
    "Daddy-Daughter Card Wars
    "Two Swords"
    "High Strangeness" (non-speaking cameo)
    "Mysterious Island"
    "Hide and Seek"
    "Min and Marty"
    "Helpers"
    "Hero Heart" (as Gummy BMO)
    "Skyhooks II"
    "Abstract"
    "Fionna and Cake and Fionna"
    "Whispers" (flashback)
    "Three Buckets"
    "Son of Rap Bear"
    "Bonnibel Bubblegum"
    "Blenanas"
    "The Bird in the Clock"
    "The Insect That Sang"
    "The Worm and his Orchard" (painball memory)
    "The Bear and the Rose"