/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-124567-g0857141823-20260521"
#endif /* AVUTIL_FFVERSION_H */
